# we need a separate file since python is not available in the container,
# but required in the workspace due to pyo3 / maturin builds
[workspace]
members = ["rust/*"]

[patch.crates-io]
object_store = { git = "https://github.com/apache/arrow-rs", rev = "86446ea88b6fc3e11b47aeedb9eb24f4d69b2f13" }
