site_name: Flight Fusion
repo_url: https://github.com/roeap/flight-fusion

theme:
  name: "material"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: material/toggle-switch
        name: "Switch to light mode"

markdown_extensions:
  - def_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview: index.md
  - Advanced: advanced_tutorial.md
  - Architecture: service.md
