[package]
name = "fusion-object-store"
version = "0.1.0"
edition = "2021"
authors = ["Robert Pack <robstar.pack@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io dependencies
object_store = "0.4"
pyo3 = { version = "~0.16.5", features = [
  "extension-module",
  "abi3",
  "abi3-py37",
] }
pyo3-asyncio = { version = "0.16", features = ["attributes", "tokio-runtime"] }
# reqwest is pulled in by object store, but not used by python binding itself
# for binary wheel best practice, statically link openssl
reqwest = { version = "*", features = ["native-tls-vendored"] }
tokio = { version = "1.0", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
] }

[lib]
name = "object_store"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "object_store._internal"
