# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import flight_fusion.proto.common_pb2 as common__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="actions.proto",
    package="flight_fusion_ipc",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\ractions.proto\x12\x11\x66light_fusion_ipc\x1a\x0c\x63ommon.proto"f\n\x16RegisterDatasetRequest\x12\x30\n\x06\x66ormat\x18\x01 \x01(\x0e\x32 .flight_fusion_ipc.DatasetFormat\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t"*\n\x17RegisterDatasetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t""\n\x12\x44ropDatasetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"#\n\x13\x44ropDatasetResponse\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3',
    dependencies=[
        common__pb2.DESCRIPTOR,
    ],
)


_REGISTERDATASETREQUEST = _descriptor.Descriptor(
    name="RegisterDatasetRequest",
    full_name="flight_fusion_ipc.RegisterDatasetRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="format",
            full_name="flight_fusion_ipc.RegisterDatasetRequest.format",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="path",
            full_name="flight_fusion_ipc.RegisterDatasetRequest.path",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="flight_fusion_ipc.RegisterDatasetRequest.name",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=152,
)


_REGISTERDATASETRESPONSE = _descriptor.Descriptor(
    name="RegisterDatasetResponse",
    full_name="flight_fusion_ipc.RegisterDatasetResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="flight_fusion_ipc.RegisterDatasetResponse.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=154,
    serialized_end=196,
)


_DROPDATASETREQUEST = _descriptor.Descriptor(
    name="DropDatasetRequest",
    full_name="flight_fusion_ipc.DropDatasetRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="flight_fusion_ipc.DropDatasetRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=198,
    serialized_end=232,
)


_DROPDATASETRESPONSE = _descriptor.Descriptor(
    name="DropDatasetResponse",
    full_name="flight_fusion_ipc.DropDatasetResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="flight_fusion_ipc.DropDatasetResponse.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=234,
    serialized_end=269,
)

_REGISTERDATASETREQUEST.fields_by_name["format"].enum_type = common__pb2._DATASETFORMAT
DESCRIPTOR.message_types_by_name["RegisterDatasetRequest"] = _REGISTERDATASETREQUEST
DESCRIPTOR.message_types_by_name["RegisterDatasetResponse"] = _REGISTERDATASETRESPONSE
DESCRIPTOR.message_types_by_name["DropDatasetRequest"] = _DROPDATASETREQUEST
DESCRIPTOR.message_types_by_name["DropDatasetResponse"] = _DROPDATASETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterDatasetRequest = _reflection.GeneratedProtocolMessageType(
    "RegisterDatasetRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERDATASETREQUEST,
        "__module__": "actions_pb2"
        # @@protoc_insertion_point(class_scope:flight_fusion_ipc.RegisterDatasetRequest)
    },
)
_sym_db.RegisterMessage(RegisterDatasetRequest)

RegisterDatasetResponse = _reflection.GeneratedProtocolMessageType(
    "RegisterDatasetResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERDATASETRESPONSE,
        "__module__": "actions_pb2"
        # @@protoc_insertion_point(class_scope:flight_fusion_ipc.RegisterDatasetResponse)
    },
)
_sym_db.RegisterMessage(RegisterDatasetResponse)

DropDatasetRequest = _reflection.GeneratedProtocolMessageType(
    "DropDatasetRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _DROPDATASETREQUEST,
        "__module__": "actions_pb2"
        # @@protoc_insertion_point(class_scope:flight_fusion_ipc.DropDatasetRequest)
    },
)
_sym_db.RegisterMessage(DropDatasetRequest)

DropDatasetResponse = _reflection.GeneratedProtocolMessageType(
    "DropDatasetResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _DROPDATASETRESPONSE,
        "__module__": "actions_pb2"
        # @@protoc_insertion_point(class_scope:flight_fusion_ipc.DropDatasetResponse)
    },
)
_sym_db.RegisterMessage(DropDatasetResponse)


# @@protoc_insertion_point(module_scope)
