"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DatasetFormat(_DatasetFormat, metaclass=_DatasetFormatEnumTypeWrapper):
    pass
class _DatasetFormat:
    V = typing.NewType('V', builtins.int)
class _DatasetFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DatasetFormat.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    DATASET_FORMAT_FILE = DatasetFormat.V(0)
    DATASET_FORMAT_DATASET = DatasetFormat.V(1)
    DATASET_FORMAT_DELTA = DatasetFormat.V(2)

DATASET_FORMAT_FILE = DatasetFormat.V(0)
DATASET_FORMAT_DATASET = DatasetFormat.V(1)
DATASET_FORMAT_DELTA = DatasetFormat.V(2)
global___DatasetFormat = DatasetFormat


class RegisterDatasetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FORMAT_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    format: global___DatasetFormat.V = ...
    path: typing.Text = ...
    name: typing.Text = ...
    def __init__(self,
        *,
        format : global___DatasetFormat.V = ...,
        path : typing.Text = ...,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["format",b"format","name",b"name","path",b"path"]) -> None: ...
global___RegisterDatasetRequest = RegisterDatasetRequest

class RegisterDatasetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text = ...
    def __init__(self,
        *,
        message : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message"]) -> None: ...
global___RegisterDatasetResponse = RegisterDatasetResponse

class DropDatasetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DropDatasetRequest = DropDatasetRequest

class DropDatasetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DropDatasetResponse = DropDatasetResponse
