# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import flight_fusion.proto.actions_pb2 as actions__pb2
import flight_fusion.proto.tickets_pb2 as tickets__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='flight_fusion_ipc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x11\x66light_fusion_ipc\x1a\ractions.proto\x1a\rtickets.proto\"\x95\x01\n\x13\x46lightActionRequest\x12=\n\x08register\x18\x01 \x01(\x0b\x32).flight_fusion_ipc.RegisterDatasetRequestH\x00\x12\x35\n\x04\x64rop\x18\x02 \x01(\x0b\x32%.flight_fusion_ipc.DropDatasetRequestH\x00\x42\x08\n\x06\x61\x63tion\"{\n\x12\x46lightDoGetRequest\x12+\n\x03sql\x18\x01 \x01(\x0b\x32\x1c.flight_fusion_ipc.SqlTicketH\x00\x12+\n\x03kql\x18\x02 \x01(\x0b\x32\x1c.flight_fusion_ipc.KqlTicketH\x00\x42\x0b\n\toperation\"\x99\x01\n\x12\x46lightDoPutRequest\x12:\n\x06memory\x18\x01 \x01(\x0b\x32(.flight_fusion_ipc.PutMemoryTableRequestH\x00\x12:\n\x06remote\x18\x02 \x01(\x0b\x32(.flight_fusion_ipc.PutRemoteTableRequestH\x00\x42\x0b\n\toperationb\x06proto3'
  ,
  dependencies=[actions__pb2.DESCRIPTOR,tickets__pb2.DESCRIPTOR,])




_FLIGHTACTIONREQUEST = _descriptor.Descriptor(
  name='FlightActionRequest',
  full_name='flight_fusion_ipc.FlightActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='register', full_name='flight_fusion_ipc.FlightActionRequest.register', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop', full_name='flight_fusion_ipc.FlightActionRequest.drop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='action', full_name='flight_fusion_ipc.FlightActionRequest.action',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=67,
  serialized_end=216,
)


_FLIGHTDOGETREQUEST = _descriptor.Descriptor(
  name='FlightDoGetRequest',
  full_name='flight_fusion_ipc.FlightDoGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql', full_name='flight_fusion_ipc.FlightDoGetRequest.sql', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kql', full_name='flight_fusion_ipc.FlightDoGetRequest.kql', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='operation', full_name='flight_fusion_ipc.FlightDoGetRequest.operation',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=218,
  serialized_end=341,
)


_FLIGHTDOPUTREQUEST = _descriptor.Descriptor(
  name='FlightDoPutRequest',
  full_name='flight_fusion_ipc.FlightDoPutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memory', full_name='flight_fusion_ipc.FlightDoPutRequest.memory', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remote', full_name='flight_fusion_ipc.FlightDoPutRequest.remote', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='operation', full_name='flight_fusion_ipc.FlightDoPutRequest.operation',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=344,
  serialized_end=497,
)

_FLIGHTACTIONREQUEST.fields_by_name['register'].message_type = actions__pb2._REGISTERDATASETREQUEST
_FLIGHTACTIONREQUEST.fields_by_name['drop'].message_type = actions__pb2._DROPDATASETREQUEST
_FLIGHTACTIONREQUEST.oneofs_by_name['action'].fields.append(
  _FLIGHTACTIONREQUEST.fields_by_name['register'])
_FLIGHTACTIONREQUEST.fields_by_name['register'].containing_oneof = _FLIGHTACTIONREQUEST.oneofs_by_name['action']
_FLIGHTACTIONREQUEST.oneofs_by_name['action'].fields.append(
  _FLIGHTACTIONREQUEST.fields_by_name['drop'])
_FLIGHTACTIONREQUEST.fields_by_name['drop'].containing_oneof = _FLIGHTACTIONREQUEST.oneofs_by_name['action']
_FLIGHTDOGETREQUEST.fields_by_name['sql'].message_type = tickets__pb2._SQLTICKET
_FLIGHTDOGETREQUEST.fields_by_name['kql'].message_type = tickets__pb2._KQLTICKET
_FLIGHTDOGETREQUEST.oneofs_by_name['operation'].fields.append(
  _FLIGHTDOGETREQUEST.fields_by_name['sql'])
_FLIGHTDOGETREQUEST.fields_by_name['sql'].containing_oneof = _FLIGHTDOGETREQUEST.oneofs_by_name['operation']
_FLIGHTDOGETREQUEST.oneofs_by_name['operation'].fields.append(
  _FLIGHTDOGETREQUEST.fields_by_name['kql'])
_FLIGHTDOGETREQUEST.fields_by_name['kql'].containing_oneof = _FLIGHTDOGETREQUEST.oneofs_by_name['operation']
_FLIGHTDOPUTREQUEST.fields_by_name['memory'].message_type = tickets__pb2._PUTMEMORYTABLEREQUEST
_FLIGHTDOPUTREQUEST.fields_by_name['remote'].message_type = tickets__pb2._PUTREMOTETABLEREQUEST
_FLIGHTDOPUTREQUEST.oneofs_by_name['operation'].fields.append(
  _FLIGHTDOPUTREQUEST.fields_by_name['memory'])
_FLIGHTDOPUTREQUEST.fields_by_name['memory'].containing_oneof = _FLIGHTDOPUTREQUEST.oneofs_by_name['operation']
_FLIGHTDOPUTREQUEST.oneofs_by_name['operation'].fields.append(
  _FLIGHTDOPUTREQUEST.fields_by_name['remote'])
_FLIGHTDOPUTREQUEST.fields_by_name['remote'].containing_oneof = _FLIGHTDOPUTREQUEST.oneofs_by_name['operation']
DESCRIPTOR.message_types_by_name['FlightActionRequest'] = _FLIGHTACTIONREQUEST
DESCRIPTOR.message_types_by_name['FlightDoGetRequest'] = _FLIGHTDOGETREQUEST
DESCRIPTOR.message_types_by_name['FlightDoPutRequest'] = _FLIGHTDOPUTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightActionRequest = _reflection.GeneratedProtocolMessageType('FlightActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTACTIONREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:flight_fusion_ipc.FlightActionRequest)
  })
_sym_db.RegisterMessage(FlightActionRequest)

FlightDoGetRequest = _reflection.GeneratedProtocolMessageType('FlightDoGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTDOGETREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:flight_fusion_ipc.FlightDoGetRequest)
  })
_sym_db.RegisterMessage(FlightDoGetRequest)

FlightDoPutRequest = _reflection.GeneratedProtocolMessageType('FlightDoPutRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTDOPUTREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:flight_fusion_ipc.FlightDoPutRequest)
  })
_sym_db.RegisterMessage(FlightDoPutRequest)


# @@protoc_insertion_point(module_scope)
