version: "3.9"
services:
  mysql:
    container_name: openmetadata_mysql
    image: openmetadata/db:0.7.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    networks:
      app_net:
        ipv4_address: 172.16.240.10

  elasticsearch:
    container_name: openmetadata_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m

    networks:
      app_net:
        ipv4_address: 172.16.240.11
    ports:
      - 9200:9200
      - 9300:9300

  openmetadata-server:
    container_name: openmetadata_server
    restart: always
    image: openmetadata/server:0.7.0
    expose:
      - 8585
      - 9200
      - 9300
      - 3306
    ports:
      - 8585:8585
    depends_on:
      - mysql
    networks:
      app_net:
        ipv4_address: 172.16.240.13
    extra_hosts:
      - "localhost:172.16.240.10"
      - "elasticsearch:172.16.240.11"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"
