---
global:
  postgresqlSecretName: "mlfusion-postgresql-secret"
  # A service account name to use for this chart and all subcharts. If this is set, then
  # mlfusion subcharts will not create their own service accounts.
  serviceAccountName: ""

nameOverride: ""
fullnameOverride: ""
# Specify secrets to run containers based on images in private registries. See:
# https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
imagePullSecrets: []

####################################################################################################
# Mlflow: Configuration for the Mlflow web server
####################################################################################################
mlflow:
  enabled: true

####################################################################################################
# Mlserver: Configuration for the Mlserver web server
####################################################################################################
mlserver:
  enabled: true

####################################################################################################
# Extra Manifests: (Optional) Create additional k8s resources within this chart
####################################################################################################
extraManifests: []
