apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-fusion.fullname" . }}
  labels:
    {{- include "flight-fusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: flight-fusion
spec:
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: flight
  selector:
    {{- include "flight-fusion.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flight-fusion
