apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: ./postgres-db-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staroid-role
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "pods/log",
        "pods/exec",
        "pods/binding",
        "services",
        "secrets",
        "configmaps",
        "persistentvolumeclaims",
      ]
    verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["crt-user-psp"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staroid-rolebinding
roleRef:
  kind: Role
  name: staroid-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
---
