/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddLineage {
    /// User provided description of the lineage details.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "edge")]
    pub edge: Box<crate::models::EntitiesEdge>,
}

impl AddLineage {
    pub fn new(edge: crate::models::EntitiesEdge) -> AddLineage {
        AddLineage {
            description: None,
            edge: Box::new(edge),
        }
    }
}
