/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ColumnProfile {
    /// Column Name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// No. of unique values in the column.
    #[serde(rename = "uniqueCount", skip_serializing_if = "Option::is_none")]
    pub unique_count: Option<f64>,
    /// Proportion of number of unique values in a column.
    #[serde(rename = "uniqueProportion", skip_serializing_if = "Option::is_none")]
    pub unique_proportion: Option<f64>,
    /// No.of null values in a column.
    #[serde(rename = "nullCount", skip_serializing_if = "Option::is_none")]
    pub null_count: Option<f64>,
    /// No.of null value proportion in columns.
    #[serde(rename = "nullProportion", skip_serializing_if = "Option::is_none")]
    pub null_proportion: Option<f64>,
    /// Minimum value in a column.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<String>,
    /// Maximum value in a column.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
    /// Avg value in a column.
    #[serde(rename = "mean", skip_serializing_if = "Option::is_none")]
    pub mean: Option<String>,
    /// Median value in a column.
    #[serde(rename = "median", skip_serializing_if = "Option::is_none")]
    pub median: Option<String>,
    /// Standard deviation of a column.
    #[serde(rename = "stddev", skip_serializing_if = "Option::is_none")]
    pub stddev: Option<f64>,
}

impl ColumnProfile {
    pub fn new() -> ColumnProfile {
        ColumnProfile {
            name: None,
            unique_count: None,
            unique_proportion: None,
            null_count: None,
            null_proportion: None,
            min: None,
            max: None,
            mean: None,
            median: None,
            stddev: None,
        }
    }
}
