/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTagCategory {
    /// Name of the tag.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the tag category
    #[serde(rename = "description")]
    pub description: String,
    /// Type of tag category.
    #[serde(rename = "categoryType")]
    pub category_type: CategoryType,
}

impl CreateTagCategory {
    pub fn new(
        name: String,
        description: String,
        category_type: CategoryType,
    ) -> CreateTagCategory {
        CreateTagCategory {
            name,
            description,
            category_type,
        }
    }
}

/// Type of tag category.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryType {
    #[serde(rename = "Descriptive")]
    Descriptive,
    #[serde(rename = "Classification")]
    Classification,
}

impl Default for CategoryType {
    fn default() -> CategoryType {
        Self::Descriptive
    }
}
