/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDatabase {
    /// Name that identifies the database.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the database instance. What it has and how to use it.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::EntityReference>>,
    #[serde(rename = "service")]
    pub service: Box<crate::models::EntityReference>,
}

impl CreateDatabase {
    pub fn new(name: String, service: crate::models::EntityReference) -> CreateDatabase {
        CreateDatabase {
            name,
            description: None,
            owner: None,
            service: Box::new(service),
        }
    }
}
