/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTag {
    /// Name of the tag.
    #[serde(rename = "name")]
    pub name: String,
    /// Unique name of the tag category
    #[serde(rename = "description")]
    pub description: String,
    /// Fully qualified names of tags associated with this tag
    #[serde(rename = "associatedTags", skip_serializing_if = "Option::is_none")]
    pub associated_tags: Option<Vec<String>>,
}

impl CreateTag {
    pub fn new(name: String, description: String) -> CreateTag {
        CreateTag {
            name,
            description,
            associated_tags: None,
        }
    }
}
