/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DailyCount {
    /// Daily count of a measurement on the given date.
    #[serde(rename = "count")]
    pub count: i32,
    /// Date in ISO 8601 format in UTC. Example - '2018-11-13'.
    #[serde(rename = "date")]
    pub date: String,
}

impl DailyCount {
    pub fn new(count: i32, date: String) -> DailyCount {
        DailyCount { count, date }
    }
}
