/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Edge {
    /// Unique id used to identify an entity.
    #[serde(rename = "fromEntity", skip_serializing_if = "Option::is_none")]
    pub from_entity: Option<String>,
    /// Unique id used to identify an entity.
    #[serde(rename = "toEntity", skip_serializing_if = "Option::is_none")]
    pub to_entity: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Edge {
    pub fn new() -> Edge {
        Edge {
            from_entity: None,
            to_entity: None,
            description: None,
        }
    }
}
