/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EntityHistory {
    /// Entity type, such as `database`, `table`, `dashboard`, for which this version history is produced.
    #[serde(rename = "entityType")]
    pub entity_type: String,
    #[serde(rename = "versions")]
    pub versions: Vec<serde_json::Value>,
}

impl EntityHistory {
    pub fn new(entity_type: String, versions: Vec<serde_json::Value>) -> EntityHistory {
        EntityHistory {
            entity_type,
            versions,
        }
    }
}
