/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FieldChange {
    /// Name of the field of an entity.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Previous value of the field. Note that this is a JSON string and use the corresponding field type to deserialize it.
    #[serde(rename = "oldValue", skip_serializing_if = "Option::is_none")]
    pub old_value: Option<serde_json::Value>,
    /// New value of the field. Note that this is a JSON string and use the corresponding field type to deserialize it.
    #[serde(rename = "newValue", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<serde_json::Value>,
}

impl FieldChange {
    pub fn new() -> FieldChange {
        FieldChange {
            name: None,
            old_value: None,
            new_value: None,
        }
    }
}
