/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IngestionStatus {
    /// Workflow status denotes if its failed or succeeded.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// startDate of the Ingestion Pipeline run for this particular execution.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// endDate of the Ingestion pipeline run for this particular execution.
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
}

impl IngestionStatus {
    pub fn new() -> IngestionStatus {
        IngestionStatus {
            state: None,
            start_date: None,
            end_date: None,
        }
    }
}
