/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JoinedWith {
    /// Fully qualified name of the column that includes `serviceName.databaseName.tableName.columnName[.nestedColumnName]`. When columnName is null for dataType struct fields, `field_#` where `#` is field index is used. For map dataType, for key the field name `key` is used and for the value field `value` is used.
    #[serde(rename = "fullyQualifiedName", skip_serializing_if = "Option::is_none")]
    pub fully_qualified_name: Option<String>,
    #[serde(rename = "joinCount", skip_serializing_if = "Option::is_none")]
    pub join_count: Option<i32>,
}

impl JoinedWith {
    pub fn new() -> JoinedWith {
        JoinedWith {
            fully_qualified_name: None,
            join_count: None,
        }
    }
}
