/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Paging {
    /// Before cursor used for getting the previous page (see API pagination for details).
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
    /// After cursor used for getting the next page (see API pagination for details).
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Total number of entries available to page through.
    #[serde(rename = "total")]
    pub total: i32,
}

impl Paging {
    pub fn new(total: i32) -> Paging {
        Paging {
            before: None,
            after: None,
            total,
        }
    }
}
