/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Policy {
    /// Unique id used to identify an entity.
    #[serde(rename = "id")]
    pub id: String,
    /// Name that identifies this Policy.
    #[serde(rename = "name")]
    pub name: String,
    /// Name that uniquely identifies a Policy.
    #[serde(rename = "fullyQualifiedName", skip_serializing_if = "Option::is_none")]
    pub fully_qualified_name: Option<String>,
    /// Title for this Policy.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// A short description of the Policy, comprehensible to regular users.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::EntityReference>>,
    /// Link to a well documented definition of this Policy.
    #[serde(rename = "policyUrl", skip_serializing_if = "Option::is_none")]
    pub policy_url: Option<String>,
    /// URI that points to a resource.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// This schema defines the type used for describing different types of policies.
    #[serde(rename = "policyType")]
    pub policy_type: PolicyType,
    /// Is the policy enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Metadata version of the entity in the form `Major.Minor`. First version always starts from `0.1` when the entity is created. When the backward compatible changes are made to the entity, only the `Minor` version is incremented - example `1.0` is changed to `1.1`. When backward incompatible changes are made the `Major` version is incremented - example `1.1` to `2.0`.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<f64>,
    /// Date and time in ISO 8601 format. Example - '2018-11-13T20:20:39+00:00'.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// User who made the update.
    #[serde(rename = "updatedBy", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<String>,
    #[serde(rename = "changeDescription", skip_serializing_if = "Option::is_none")]
    pub change_description: Option<Box<crate::models::ChangeDescription>>,
    /// A set of rules associated with the Policy.
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<serde_json::Value>>,
}

impl Policy {
    pub fn new(id: String, name: String, policy_type: PolicyType) -> Policy {
        Policy {
            id,
            name,
            fully_qualified_name: None,
            display_name: None,
            description: None,
            owner: None,
            policy_url: None,
            href: None,
            policy_type,
            enabled: None,
            version: None,
            updated_at: None,
            updated_by: None,
            change_description: None,
            rules: None,
        }
    }
}

/// This schema defines the type used for describing different types of policies.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PolicyType {
    #[serde(rename = "AccessControl")]
    AccessControl,
    #[serde(rename = "Lifecycle")]
    Lifecycle,
}

impl Default for PolicyType {
    fn default() -> PolicyType {
        Self::AccessControl
    }
}
