/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TableProfile {
    /// Date in ISO 8601 format in UTC. Example - '2018-11-13'.
    #[serde(rename = "profileDate", skip_serializing_if = "Option::is_none")]
    pub profile_date: Option<String>,
    /// No.of columns in the table.
    #[serde(rename = "columnCount", skip_serializing_if = "Option::is_none")]
    pub column_count: Option<f64>,
    /// No.of rows in the table.
    #[serde(rename = "rowCount", skip_serializing_if = "Option::is_none")]
    pub row_count: Option<f64>,
    /// List of local column profiles of the table.
    #[serde(rename = "columnProfile", skip_serializing_if = "Option::is_none")]
    pub column_profile: Option<Vec<crate::models::ColumnProfile>>,
}

impl TableProfile {
    pub fn new() -> TableProfile {
        TableProfile {
            profile_date: None,
            column_count: None,
            row_count: None,
            column_profile: None,
        }
    }
}
