/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Topic {
    /// Unique id used to identify an entity.
    #[serde(rename = "id")]
    pub id: String,
    /// Name that identifies a topic.
    #[serde(rename = "name")]
    pub name: String,
    /// Name that uniquely identifies a topic in the format 'messagingServiceName.topicName'.
    #[serde(rename = "fullyQualifiedName", skip_serializing_if = "Option::is_none")]
    pub fully_qualified_name: Option<String>,
    /// Display Name that identifies this topic. It could be title or label from the source services.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Description of the topic instance.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Metadata version of the entity in the form `Major.Minor`. First version always starts from `0.1` when the entity is created. When the backward compatible changes are made to the entity, only the `Minor` version is incremented - example `1.0` is changed to `1.1`. When backward incompatible changes are made the `Major` version is incremented - example `1.1` to `2.0`.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<f64>,
    /// Date and time in ISO 8601 format. Example - '2018-11-13T20:20:39+00:00'.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// User who made the update.
    #[serde(rename = "updatedBy", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<String>,
    #[serde(rename = "service")]
    pub service: Box<crate::models::EntityReference>,
    /// Type of messaging service - Kafka or Pulsar.
    #[serde(rename = "serviceType", skip_serializing_if = "Option::is_none")]
    pub service_type: Option<ServiceType>,
    /// Number of partitions into which the topic is divided.
    #[serde(rename = "partitions")]
    pub partitions: i32,
    /// Schema used for message serialization. Optional as some topics may not have associated schemas.
    #[serde(rename = "schemaText", skip_serializing_if = "Option::is_none")]
    pub schema_text: Option<String>,
    /// Schema type used for the message.
    #[serde(rename = "schemaType", skip_serializing_if = "Option::is_none")]
    pub schema_type: Option<SchemaType>,
    /// Topic clean up policies. For Kafka - `cleanup.policy` configuration.
    #[serde(rename = "cleanupPolicies", skip_serializing_if = "Option::is_none")]
    pub cleanup_policies: Option<Vec<CleanupPolicies>>,
    /// Retention time in milliseconds. For Kafka - `retention.ms` configuration.
    #[serde(rename = "retentionTime", skip_serializing_if = "Option::is_none")]
    pub retention_time: Option<f64>,
    /// Replication Factor in integer (more than 1).
    #[serde(rename = "replicationFactor", skip_serializing_if = "Option::is_none")]
    pub replication_factor: Option<i32>,
    /// Maximum message size in bytes. For Kafka - `max.message.bytes` configuration.
    #[serde(rename = "maximumMessageSize", skip_serializing_if = "Option::is_none")]
    pub maximum_message_size: Option<i32>,
    /// Minimum number replicas in sync to control durability. For Kafka - `min.insync.replicas` configuration.
    #[serde(
        rename = "minimumInSyncReplicas",
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_in_sync_replicas: Option<i32>,
    /// Maximum size of a partition in bytes before old data is discarded. For Kafka - `retention.bytes` configuration.
    #[serde(rename = "retentionSize", skip_serializing_if = "Option::is_none")]
    pub retention_size: Option<f64>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::EntityReference>>,
    #[serde(rename = "followers", skip_serializing_if = "Option::is_none")]
    pub followers: Option<Vec<crate::models::EntityReference>>,
    /// Tags for this table.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::TagLabel>>,
    /// URI that points to a resource.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "changeDescription", skip_serializing_if = "Option::is_none")]
    pub change_description: Option<Box<crate::models::ChangeDescription>>,
}

impl Topic {
    pub fn new(
        id: String,
        name: String,
        service: crate::models::EntityReference,
        partitions: i32,
    ) -> Topic {
        Topic {
            id,
            name,
            fully_qualified_name: None,
            display_name: None,
            description: None,
            version: None,
            updated_at: None,
            updated_by: None,
            service: Box::new(service),
            service_type: None,
            partitions,
            schema_text: None,
            schema_type: None,
            cleanup_policies: None,
            retention_time: None,
            replication_factor: None,
            maximum_message_size: None,
            minimum_in_sync_replicas: None,
            retention_size: None,
            owner: None,
            followers: None,
            tags: None,
            href: None,
            change_description: None,
        }
    }
}

/// Type of messaging service - Kafka or Pulsar.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceType {
    #[serde(rename = "Kafka")]
    Kafka,
    #[serde(rename = "Pulsar")]
    Pulsar,
}

impl Default for ServiceType {
    fn default() -> ServiceType {
        Self::Kafka
    }
}
/// Schema type used for the message.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaType {
    #[serde(rename = "Avro")]
    Avro,
    #[serde(rename = "Protobuf")]
    Protobuf,
    #[serde(rename = "JSON")]
    JSON,
    #[serde(rename = "Other")]
    Other,
}

impl Default for SchemaType {
    fn default() -> SchemaType {
        Self::Avro
    }
}
/// Topic clean up policies. For Kafka - `cleanup.policy` configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CleanupPolicies {
    #[serde(rename = "DELETE")]
    DELETE,
    #[serde(rename = "COMPACT")]
    COMPACT,
}

impl Default for CleanupPolicies {
    fn default() -> CleanupPolicies {
        Self::DELETE
    }
}
