/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsageDetails {
    #[serde(rename = "dailyStats")]
    pub daily_stats: Box<crate::models::UsageStats>,
    #[serde(rename = "weeklyStats", skip_serializing_if = "Option::is_none")]
    pub weekly_stats: Option<Box<crate::models::UsageStats>>,
    #[serde(rename = "monthlyStats", skip_serializing_if = "Option::is_none")]
    pub monthly_stats: Option<Box<crate::models::UsageStats>>,
    /// Date in ISO 8601 format in UTC. Example - '2018-11-13'.
    #[serde(rename = "date")]
    pub date: String,
}

impl UsageDetails {
    pub fn new(daily_stats: crate::models::UsageStats, date: String) -> UsageDetails {
        UsageDetails {
            daily_stats: Box::new(daily_stats),
            weekly_stats: None,
            monthly_stats: None,
            date,
        }
    }
}
