/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    /// Unique id used to identify an entity.
    #[serde(rename = "id")]
    pub id: String,
    /// A unique name of the user, typically the user ID from an identity provider. Example - uid from LDAP.
    #[serde(rename = "name")]
    pub name: String,
    /// Used for user biography.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name used for display purposes. Example 'FirstName LastName'.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Metadata version of the entity in the form `Major.Minor`. First version always starts from `0.1` when the entity is created. When the backward compatible changes are made to the entity, only the `Minor` version is incremented - example `1.0` is changed to `1.1`. When backward incompatible changes are made the `Major` version is incremented - example `1.1` to `2.0`.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<f64>,
    /// Date and time in ISO 8601 format. Example - '2018-11-13T20:20:39+00:00'.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// User who made the update.
    #[serde(rename = "updatedBy", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<String>,
    /// Email address of a user or other entities.
    #[serde(rename = "email")]
    pub email: String,
    /// URI that points to a resource.
    #[serde(rename = "href")]
    pub href: String,
    /// Timezone of the user.
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// When true indicates the user has been deactivated. Users are deactivated instead of deleted.
    #[serde(rename = "deactivated", skip_serializing_if = "Option::is_none")]
    pub deactivated: Option<bool>,
    /// When true indicates a special type of user called Bot.
    #[serde(rename = "isBot", skip_serializing_if = "Option::is_none")]
    pub is_bot: Option<bool>,
    /// When true indicates user is an administrator for the system with superuser privileges.
    #[serde(rename = "isAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<Box<crate::models::Profile>>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<crate::models::EntityReference>>,
    #[serde(rename = "owns", skip_serializing_if = "Option::is_none")]
    pub owns: Option<Vec<crate::models::EntityReference>>,
    #[serde(rename = "follows", skip_serializing_if = "Option::is_none")]
    pub follows: Option<Vec<crate::models::EntityReference>>,
    #[serde(rename = "changeDescription", skip_serializing_if = "Option::is_none")]
    pub change_description: Option<Box<crate::models::ChangeDescription>>,
}

impl User {
    pub fn new(id: String, name: String, email: String, href: String) -> User {
        User {
            id,
            name,
            description: None,
            display_name: None,
            version: None,
            updated_at: None,
            updated_by: None,
            email,
            href,
            timezone: None,
            deactivated: None,
            is_bot: None,
            is_admin: None,
            profile: None,
            teams: None,
            owns: None,
            follows: None,
            change_description: None,
        }
    }
}
