apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-env-mlflow
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MLFLOW_TRACKING_URI: "http://mlflow.{{.Namespace}}:5000"
---
{{- if .Values.mlserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-env-mlserver
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MLSERVER_INFERRENCE_URI: "http://mlserver.{{.Namespace}}:5000"
{{- end }}
