name: Python Release Build
on:
  push:
    tags:
      - "python-v*"

jobs:
  build-python-mac-win:
    name: Mac/Win
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==0.12.6

      - name: Build Python package
        # run: maturin build --release --no-sdist --strip --locked
        run: make python-build

      - name: List Windows wheels
        if: matrix.os == 'windows-latest'
        run: dir target\wheels\

      - name: List Mac wheels
        if: matrix.os != 'windows-latest'
        run: find target/wheels/

      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: target/wheels/*

  # build-manylinux:
  #   name: Manylinux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Build wheels
  #       run: |
  #         export RUSTFLAGS='-C target-cpu=skylake'
  #         docker run --rm -v $(pwd)/..:/io \
  #           --workdir /io \
  #           konstin2/maturin:v0.12.6 \
  #           build --release --manylinux 2010 --locked
  #
  #     - name: Archive wheels
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         path: target/wheels/*
