class Path:
    def __init__(self, raw: str | list[str]) -> None: ...
    def child(self, part: str) -> Path: ...

class ObjectStore:
    def __init__(self, root: str) -> None: ...
    def get(self, location: Path) -> bytes: ...
    def put(self, location: Path, bytes: bytes) -> None: ...
